import { EmailMessage, FollowUpReminder } from './types';

export const CLIENT_SIMULATED_EMAILS: EmailMessage[] = [
  {
    id: 'sim-msg-1',
    threadId: 'sim-thread-1',
    sender: 'Sarah Jenkins <sarah.j@acme-corp.com>',
    senderName: 'Sarah Jenkins',
    senderEmail: 'sarah.j@acme-corp.com',
    subject: 'Urgent: Review required for Q3 Marketing Strategy & Budget allocation',
    body: 'Hi team,\n\nI hope you are having a productive week. We have finalized the draft for the Q3 Marketing Strategy and Budget allocation. Please review the attached deck and provide feedback by end of day Friday so we can lock in the budget.\n\nAlso, John, could you please update the conversion projection numbers on slide 14 before the executive meeting on Monday?\n\nThanks,\nSarah',
    snippet: 'Please review the attached deck and provide feedback by end of day Friday so we can lock in the budget.',
    date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Urgent Bills',
    isRead: false,
  },
  {
    id: 'sim-msg-2',
    threadId: 'sim-thread-2',
    sender: 'GitHub Security <noreply@github.com>',
    senderName: 'GitHub Security',
    senderEmail: 'noreply@github.com',
    subject: '[GitHub] Alert: 3 vulnerabilities found in npm dependencies',
    body: 'Hello @draftly-user,\n\nWe found 3 known security vulnerabilities in your npm dependencies for project draftly-email-agent:\n- high: prototype pollution in lodash\n- moderate: regular expression denial of service in ws\n- low: information exposure in express\n\nPlease run "npm audit fix" or update package-lock.json to resolve these issues immediately to secure your deployment.\n\nAutomated Security Team',
    snippet: 'We found 3 known security vulnerabilities in your npm dependencies for project draftly-email-agent...',
    date: new Date(Date.now() - 3600000 * 2).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Work',
    isRead: false,
  },
  {
    id: 'sim-msg-3',
    threadId: 'sim-thread-3',
    sender: 'Alex Rivera <alex.rivera@figma.com>',
    senderName: 'Alex Rivera',
    senderEmail: 'alex.rivera@figma.com',
    subject: 'Alex Rivera commented on "Draftly UI Redesign V2"',
    body: 'Alex Rivera left a comment on Draftly UI Redesign V2:\n\n"I love this high-contrast monochrome dark aesthetic! Let\'s make sure the status ticker marquee at the bottom has a subtle speed, and that the typography uses a classic serif font for main headers to give it that bespoke editorial look. Let\'s finalize this design tomorrow!"',
    snippet: 'Alex Rivera left a comment on Draftly UI Redesign V2: "I love this high-contrast monochrome dark aesthetic!"',
    date: new Date(Date.now() - 3600000 * 5).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Work',
    isRead: true,
  },
  {
    id: 'sim-msg-4',
    threadId: 'sim-thread-4',
    sender: 'Stripe Billing <billing@stripe.com>',
    senderName: 'Stripe Billing',
    senderEmail: 'billing@stripe.com',
    subject: 'Your receipt for Stripe Invoice #ST-9921820',
    body: 'Hi there,\n\nThanks for your payment! This is a receipt for your Stripe subscription invoice #ST-9921820. Your credit card has been charged $49.00 USD for the Premium Tier.\n\nIf you have any questions or need to update your VAT ID or billing address, please visit your billing settings.\n\nStripe Team',
    snippet: 'This is a receipt for your Stripe subscription invoice #ST-9921820. Your credit card has been charged $49.00 USD.',
    date: new Date(Date.now() - 3600000 * 12).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Urgent Bills',
    isRead: true,
  },
  {
    id: 'sim-msg-5',
    threadId: 'sim-thread-5',
    sender: 'Uber Receipts <uber.us@uber.com>',
    senderName: 'Uber Receipts',
    senderEmail: 'uber.us@uber.com',
    subject: 'Your Friday evening ride with Uber - $24.50',
    body: 'Thanks for riding, Draftly User!\n\nHere is your receipt for your ride on Friday evening. \nTotal: $24.50\nDistance: 5.4 miles\nDuration: 18 mins\nDriver: Carlos (5.0 ★)\n\nTo view a map of your route or request assistance with a lost item, please head to your Uber app.',
    snippet: 'Here is your receipt for your ride on Friday evening. Total: $24.50.',
    date: new Date(Date.now() - 3600000 * 24).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Primary',
    isRead: true,
  },
  {
    id: 'sim-msg-6',
    threadId: 'sim-thread-6',
    sender: 'LinkedIn <updates@linkedin.com>',
    senderName: 'LinkedIn',
    senderEmail: 'updates@linkedin.com',
    subject: 'Michael Chen and 2 others viewed your profile this week',
    body: 'Hi Draftly User,\n\nMichael Chen (Product Lead at Google AI) and 2 other people viewed your profile this week. See what else is happening in your network: discover new opportunities, read trending industry newsletters, and expand your professional reach.\n\nSee all views on LinkedIn.',
    snippet: 'Michael Chen (Product Lead at Google AI) and 2 other people viewed your profile this week.',
    date: new Date(Date.now() - 3600000 * 36).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Social',
    isRead: false,
    unsubscribeUrl: 'https://www.linkedin.com/unsubscribe?id=sim-6',
  },
  {
    id: 'sim-msg-7',
    threadId: 'sim-thread-7',
    sender: 'Netflix <info@netflix.com>',
    senderName: 'Netflix',
    senderEmail: 'info@netflix.com',
    subject: 'New Show Alert: "The Code Architect" is now streaming',
    body: 'Hey Draftly User,\n\nWe just added a new thriller series you might love: "The Code Architect". Based on a true story of a sandboxed system optimization in a terminal. Watch it now on Netflix.\n\nHappy Streaming,\nThe Netflix Team',
    snippet: 'We just added a new thriller series you might love: "The Code Architect". Watch it now on Netflix.',
    date: new Date(Date.now() - 3600000 * 48).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Promotions',
    isRead: false,
    unsubscribeUrl: 'https://netflix.com/unsubscribe?id=sim-7',
  },
  {
    id: 'sim-msg-8',
    threadId: 'sim-thread-8',
    sender: 'TLDR Tech <newsletter@tldr.com>',
    senderName: 'TLDR Tech',
    senderEmail: 'newsletter@tldr.com',
    subject: 'TLDR Tech: The rise of customized, autonomous inbox agents',
    body: 'Hi Reader,\n\nIn today\'s edition, we explore how customized corporate and personal inbox sorting agents are drastically saving time for knowledge workers. Leveraging cognitive lightweight models to summarize complex content has shown a 34% reduction in daily communication overhead.\n\nRead the full report on our website.',
    snippet: 'In today\'s edition, we explore how customized corporate and personal inbox sorting agents are saving time...',
    date: new Date(Date.now() - 3600000 * 60).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Newsletters',
    isRead: false,
    unsubscribeUrl: 'https://tldr.tech/unsubscribe?id=sim-8',
  },
  {
    id: 'sim-msg-9',
    threadId: 'sim-thread-9',
    sender: 'Crypto Moon <win@cryptorewards-win.com>',
    senderName: 'Crypto Moon',
    senderEmail: 'win@cryptorewards-win.com',
    subject: 'CONGRATULATIONS! You won 10,000 Free BTC Tokens!',
    body: 'DEAR FRIEND!! YOU ARE SELECTED!!\n\nYour email has won 10,000 FREE CRYPTO TOKENS! Click this secure link right now to claim your immediate air-dropped tokens before they expire in 2 hours:\n\nCLAIM_TOKENS_SECURE_LINK_99182\n\nNo verification needed, act fast!',
    snippet: 'YOUR EMAIL HAS WON 10,000 FREE CRYPTO TOKENS! Click this secure link right now to claim...',
    date: new Date(Date.now() - 3600000 * 72).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Spam',
    isRead: false,
    unsubscribeMailto: 'mailto:unsub@cryptorewards-win.com?subject=unsubscribe-sim-9',
  },
  {
    id: 'sim-msg-10',
    threadId: 'sim-thread-10',
    sender: 'David Miller <d.miller@acme-corp.com>',
    senderName: 'David Miller',
    senderEmail: 'd.miller@acme-corp.com',
    subject: 'Acme Q3 Project Roadmap & Deliverables list',
    body: 'Hi all,\n\nWe need to align on our roadmap deliverables for Q3. Here is the draft schedule:\n- July 15: Draftly Core system deployment\n- August 1: Multiple auth providers integration (including Apple sign-in)\n- August 15: Global client settings release\n\nPlease let me know if there are any timeline concerns by Friday morning.\n\nCheers,\nDavid',
    snippet: 'We need to align on our roadmap deliverables for Q3. Here is the draft schedule...',
    date: new Date(Date.now() - 3600000 * 84).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    category: 'Work',
    isRead: true,
  }
];

export const CLIENT_SIMULATED_FOLLOW_UPS: FollowUpReminder[] = [
  {
    id: 'sim-followup-1',
    threadId: 'sim-thread-f1',
    recipientName: 'Sarah Jenkins',
    recipientEmail: 'sarah.j@acme-corp.com',
    subject: 'Review required for Q3 Marketing Strategy & Budget allocation',
    body: 'Hi Sarah, I wanted to follow up and see if you had any comments on the Q3 Marketing Strategy and Budget allocation proposal? Let me know when you have a moment to review.',
    date: new Date(Date.now() - 3600000 * 24 * 4).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    daysAgo: 4,
  },
  {
    id: 'sim-followup-2',
    threadId: 'sim-thread-f2',
    recipientName: 'David Jones',
    recipientEmail: 'david.jones@figma.com',
    subject: 'Partnership Agreement Revision V2',
    body: 'Hi David, just checking in to see if you have any questions on the revised draft of the partnership agreement? We are aiming to finalize this by Friday.',
    date: new Date(Date.now() - 3600000 * 24 * 5).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    daysAgo: 5,
  }
];
